<?php
$labels = array();
$labels['vacation'] = 'Vacances';
$labels['autoreply'] = 'Enviar una notificació';
$labels['outofoffice'] = 'Notificació de vacances (Fora de l\'Oficina)';
$labels['autoreplysubject'] = 'Assumpte d\'autoresposta';
$labels['autoreplymessage'] = 'Missatge d\'autoresposta';
$labels['autoreplybutton'] = 'Desar';
$labels['mailforward'] = 'Reenviament de correu';
$labels['separate_alias'] = 'Separar cada àlies d\'adreça amb una coma';
$labels['separate_forward'] = 'Separar cada adreça de reenviament amb una coma';
$labels['keepcopy'] = 'Desar una còpia del correu';
$labels['forwardingaddresses'] = 'Reenviar el correu cap a';
$labels['forward'] = 'Configuracions de reenviament';
$labels['success_changed'] = 'Configuracions de vacances canviades satisfactòriament';
$labels['failed'] = 'Ha fallat el canvi de vacances!';
$labels['aliases'] = 'Àlies';
// Button text
$labels['aliasesbutton'] = 'Obté àlies';?>