<?php
$labels = array();
$labels['vacation'] = 'Dovolená';
$labels['autoreply'] = 'Poslat automatickou odpověď';
$labels['outofoffice'] = 'Automatická odpověď / Přeposílání';
$labels['autoreplysubject'] = 'Předmět zprávy';
$labels['autoreplymessage'] = 'Zpráva';
$labels['autoreplybutton'] = 'Ulož';
$labels['mailforward'] = 'Přeposílání';
$labels['aliases'] = 'Alias';
$labels['keepcopy'] = 'Zachovat kopii zprávy ve schránce';
//$labels['forwardingaddresses'] = 'Přesměrovat na';
$labels['forward'] = 'Nastavení přesměrování';
$labels['success_changed'] = 'Nastavení bylo úspěšně změněno';
$labels['failed'] = 'Automatickou odpověď / Přeposílání se nepodařilo nastavit!';
//$labels['separateaddresses'] = 'Více adres oddělujte čárkou';
//$labels['separateaddresses'] = 'Více adres oddělujte čárkou';
$labels['separate_alias'] = 'Oddělte více adres čárkou';
$labels['separate_forward'] = 'Oddělte více adres čárkou';
?>
