<?php
$labels = array();
$labels['vacation'] = 'Poissaoloviestit';
$labels['autoreply'] = "Lähetä poissaoloviesti";
$labels['outofoffice'] = 'Poissaoloviesti';
$labels['autoreplysubject'] = 'Viestin otsikko';
$labels['autoreplymessage'] = 'Viesti';
$labels['autoreplybutton'] = 'Talenna';
$labels['mailforward'] = 'Välitä sähköpostini';
$labels['separate_alias'] = 'Aliakset eivät käytössä';
$labels['separate_forward'] = 'Anna sähköpostiosoitteet erottaen ne pilkulla.';
$labels['keepcopy'] = 'Jätä kopio itsellesi vastaanotetuista sähköposteista';
$labels['forwardingaddresses'] = 'Välitä sähkköposti osoitteisiin';
$labels['forward'] = 'Välitä asetukset';
$labels['success_changed'] = 'Poissaoloasetukset tallentuivat onnistuneesti';
$labels['failed'] = 'Poissaolo asetukset epäonnistuivat';
$labels['aliases'] = 'Alias osoitteet';
// Button text
$labels['aliasesbutton'] = 'Hae aliakset';
?>
