<?php
$labels = array();
$labels['vacation'] = 'Absence et réexpédition';
$labels['autoreply'] = 'Activer le message d\'absence';
$labels['outofoffice'] = 'Message d\'absence';
$labels['autoreplysubject'] = 'Sujet du message';
$labels['autoreplymessage'] = 'Corps du message';
$labels['autoreplybutton'] = 'Sauvegarder';
$labels['mailforward'] = 'réexpedition de mail';
$labels['separate_alias'] = 'Indiquez vos diffèrents alias en les séparant par une virgule';
$labels['separate_forward'] = 'Indiquez vos diffèrentes adresse de réexpedition en les séparant par une virgule';
$labels['keepcopy'] = 'Garder une copie du mail';
$labels['forwardingaddresses'] = 'Adresse(s) de réexpédition';
$labels['forward'] = 'Options de réexpédition du courrier';
$labels['success_changed'] = 'Message d\'absence correctement configuré';
$labels['failed'] = 'Erreur lors de l\'application des options du message d\'absence';
$labels['aliases'] = 'Alias de messagerie :';
// Button text
$labels['aliasesbutton'] = 'Obtenir les alias';?>