<?php
$labels = array();
$labels['vacation'] = 'OutOfOffice';
$labels['autoreply'] = "Enviar notifica&ccedil;&atilde;o";
$labels['outofoffice'] = 'Notifica&ccedil;&atilde;o de F&eacute;rias (Out of Office)';
$labels['autoreplysubject'] = 'Assunto';
$labels['autoreplymessage'] = 'Mensagem';
$labels['autoreplybutton'] = 'Gravar';
$labels['mailforward'] = 'Reencaminhamento';
$labels['separate_alias'] = 'Separar cada endere&ccedil;o com v&iacute;rgula';
$labels['separate_forward'] = 'Separar cada destinat&aacute;rio com v&iacute;rgula';
$labels['keepcopy'] = 'Guardar c&oacute;pia do e-mail';
$labels['forwardingaddresses'] = 'Reencaminhar para';
$labels['forward'] = 'Defini&ccedil;&otilde;es de reencaminhamento';
$labels['success_changed'] = 'Defini&ccedil;&otilde;es Out of Office alteradas com sucesso';
$labels['failed'] = 'Falha a instalar o aviso Out of Office!';
$labels['aliases'] = 'Aliases';
// Button text
$labels['aliasesbutton'] = 'Obter aliases';?>