<?php
$labels = array();
$labels['vacation'] = 'Semester';
$labels['autoreply'] = "Skicka ett semester medelande";
$labels['outofoffice'] = 'Semester (Inte på jobbet) meddelande';
$labels['autoreplysubject'] = 'Meddelande rubrik';
$labels['autoreplymessage'] = 'Meddelandet';
$labels['autoreplybutton'] = 'Spara';
$labels['mailforward'] = 'Skicka min e-post vidare';
$labels['separate_alias'] = 'Skriv in dina e-post adresser separera dom med ett komma tecken';
$labels['separate_forward'] = 'Skriv in dina e-post adresser som ni vill skicka vidare till, separera dom med ett komma tacken';
$labels['keepcopy'] = 'Behåll en kopia av den e-post du mottar';
$labels['forwardingaddresses'] = 'Skicka e-post vidare till';
$labels['forward'] = 'Skicka vidare Inställningar';
$labels['success_changed'] = 'Meddelande inställningar sparade med lyckat resultat';
$labels['failed'] = 'Semster inställingar misslyckades!';
$labels['aliases'] = 'E-post adresser';
// Button text
$labels['aliasesbutton'] = 'Hämta aliases';
?>
